//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.27 at 09:59:54 AM MSK 
//


package cpd.utils.model.v10502;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gk_software.cpd.server.components.export.v10502 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gk_software.cpd.server.components.export.v10502
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TRule.GlobalData }
     * 
     */
    public TRule.GlobalData createTRuleGlobalData() {
        return new TRule.GlobalData();
    }

    /**
     * Create an instance of {@link PromotionList }
     * 
     */
    public PromotionList createPromotionList() {
        return new PromotionList();
    }

    /**
     * Create an instance of {@link TRule.SimpleRebate }
     * 
     */
    public TRule.SimpleRebate createTRuleSimpleRebate() {
        return new TRule.SimpleRebate();
    }

    /**
     * Create an instance of {@link TRule.MixAndMatch.MatchingItem }
     * 
     */
    public TRule.MixAndMatch.MatchingItem createTRuleMixAndMatchMatchingItem() {
        return new TRule.MixAndMatch.MatchingItem();
    }

    /**
     * Create an instance of {@link TRule.BonusPoints }
     * 
     */
    public TRule.BonusPoints createTRuleBonusPoints() {
        return new TRule.BonusPoints();
    }

    /**
     * Create an instance of {@link TEligibility.Coupon }
     * 
     */
    public TEligibility.Coupon createTEligibilityCoupon() {
        return new TEligibility.Coupon();
    }

    /**
     * Create an instance of {@link TRule.GlobalData.RebateMethod.RebateAsCoupon.CouponPrintoutText.Line }
     * 
     */
    public TRule.GlobalData.RebateMethod.RebateAsCoupon.CouponPrintoutText.Line createTRuleGlobalDataRebateMethodRebateAsCouponCouponPrintoutTextLine() {
        return new TRule.GlobalData.RebateMethod.RebateAsCoupon.CouponPrintoutText.Line();
    }

    /**
     * Create an instance of {@link TEligibility.Item }
     * 
     */
    public TEligibility.Item createTEligibilityItem() {
        return new TEligibility.Item();
    }

    /**
     * Create an instance of {@link TRule.MixAndMatch }
     * 
     */
    public TRule.MixAndMatch createTRuleMixAndMatch() {
        return new TRule.MixAndMatch();
    }

    /**
     * Create an instance of {@link TEligibility.ManualRebateTrigger.ManualTrigger }
     * 
     */
    public TEligibility.ManualRebateTrigger.ManualTrigger createTEligibilityManualRebateTriggerManualTrigger() {
        return new TEligibility.ManualRebateTrigger.ManualTrigger();
    }

    /**
     * Create an instance of {@link TMerchandiseHierarchyGroupIDList }
     * 
     */
    public TMerchandiseHierarchyGroupIDList createTMerchandiseHierarchyGroupIDList() {
        return new TMerchandiseHierarchyGroupIDList();
    }

    /**
     * Create an instance of {@link TEligibility.ManualRebateTrigger.AutomaticalTrigger }
     * 
     */
    public TEligibility.ManualRebateTrigger.AutomaticalTrigger createTEligibilityManualRebateTriggerAutomaticalTrigger() {
        return new TEligibility.ManualRebateTrigger.AutomaticalTrigger();
    }

    /**
     * Create an instance of {@link TRule.Set.SetItem }
     * 
     */
    public TRule.Set.SetItem createTRuleSetSetItem() {
        return new TRule.Set.SetItem();
    }

    /**
     * Create an instance of {@link TTimePeriod }
     * 
     */
    public TTimePeriod createTTimePeriod() {
        return new TTimePeriod();
    }

    /**
     * Create an instance of {@link TRule.GlobalData.RebateMethod.RebateAsTender }
     * 
     */
    public TRule.GlobalData.RebateMethod.RebateAsTender createTRuleGlobalDataRebateMethodRebateAsTender() {
        return new TRule.GlobalData.RebateMethod.RebateAsTender();
    }

    /**
     * Create an instance of {@link TRule.GlobalData.RebateMethod.RebateAsCoupon }
     * 
     */
    public TRule.GlobalData.RebateMethod.RebateAsCoupon createTRuleGlobalDataRebateMethodRebateAsCoupon() {
        return new TRule.GlobalData.RebateMethod.RebateAsCoupon();
    }

    /**
     * Create an instance of {@link TEligibility.ManualRebateTrigger }
     * 
     */
    public TEligibility.ManualRebateTrigger createTEligibilityManualRebateTrigger() {
        return new TEligibility.ManualRebateTrigger();
    }

    /**
     * Create an instance of {@link Promotion }
     * 
     */
    public Promotion createPromotion() {
        return new Promotion();
    }

    /**
     * Create an instance of {@link TRule.GlobalData.RebateMethod.RebateAsGiftCert }
     * 
     */
    public TRule.GlobalData.RebateMethod.RebateAsGiftCert createTRuleGlobalDataRebateMethodRebateAsGiftCert() {
        return new TRule.GlobalData.RebateMethod.RebateAsGiftCert();
    }

    /**
     * Create an instance of {@link TRule }
     * 
     */
    public TRule createTRule() {
        return new TRule();
    }

    /**
     * Create an instance of {@link TCondition.GlobalData }
     * 
     */
    public TCondition.GlobalData createTConditionGlobalData() {
        return new TCondition.GlobalData();
    }

    /**
     * Create an instance of {@link TCondition }
     * 
     */
    public TCondition createTCondition() {
        return new TCondition();
    }

    /**
     * Create an instance of {@link TRule.Set }
     * 
     */
    public TRule.Set createTRuleSet() {
        return new TRule.Set();
    }

    /**
     * Create an instance of {@link TRule.GlobalData.RebateMethod.RebateAsCoupon.CouponPrintoutText }
     * 
     */
    public TRule.GlobalData.RebateMethod.RebateAsCoupon.CouponPrintoutText createTRuleGlobalDataRebateMethodRebateAsCouponCouponPrintoutText() {
        return new TRule.GlobalData.RebateMethod.RebateAsCoupon.CouponPrintoutText();
    }

    /**
     * Create an instance of {@link TEligibility }
     * 
     */
    public TEligibility createTEligibility() {
        return new TEligibility();
    }

    /**
     * Create an instance of {@link TEligibility.MerchandiseHierarchyGroup.IntersectionList }
     * 
     */
    public TEligibility.MerchandiseHierarchyGroup.IntersectionList createTEligibilityMerchandiseHierarchyGroupIntersectionList() {
        return new TEligibility.MerchandiseHierarchyGroup.IntersectionList();
    }

    /**
     * Create an instance of {@link Promotion.GlobalData.ExcludedTenders }
     * 
     */
    public Promotion.GlobalData.ExcludedTenders createPromotionGlobalDataExcludedTenders() {
        return new Promotion.GlobalData.ExcludedTenders();
    }

    /**
     * Create an instance of {@link TRule.GlobalData.RebateMethod.NormalRebate }
     * 
     */
    public TRule.GlobalData.RebateMethod.NormalRebate createTRuleGlobalDataRebateMethodNormalRebate() {
        return new TRule.GlobalData.RebateMethod.NormalRebate();
    }

    /**
     * Create an instance of {@link TEligibility.MerchandiseHierarchyGroup }
     * 
     */
    public TEligibility.MerchandiseHierarchyGroup createTEligibilityMerchandiseHierarchyGroup() {
        return new TEligibility.MerchandiseHierarchyGroup();
    }

    /**
     * Create an instance of {@link TItemIDList }
     * 
     */
    public TItemIDList createTItemIDList() {
        return new TItemIDList();
    }

    /**
     * Create an instance of {@link Promotion.GlobalData }
     * 
     */
    public Promotion.GlobalData createPromotionGlobalData() {
        return new Promotion.GlobalData();
    }

    /**
     * Create an instance of {@link TRule.GlobalData.RebateMethod }
     * 
     */
    public TRule.GlobalData.RebateMethod createTRuleGlobalDataRebateMethod() {
        return new TRule.GlobalData.RebateMethod();
    }

}
