//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.27 at 09:59:54 AM MSK 
//


package cpd.utils.model.v10502;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for T_Condition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_Condition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GlobalData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID" type="{}T_ExternalID" minOccurs="0"/>
 *                   &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="Resolution" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="TypeCode" type="{}T_Code1_4"/>
 *                   &lt;element name="Description" type="{}T_Description" minOccurs="0"/>
 *                   &lt;element name="OperatorDisplayName" type="{}T_Name" minOccurs="0"/>
 *                   &lt;element name="CustomerDisplayName" type="{}T_Name" minOccurs="0"/>
 *                   &lt;element name="ReceiptPrinterName" type="{}T_Name" minOccurs="0"/>
 *                   &lt;element name="TimePeriod" type="{}T_TimePeriod" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ItemDiscountControlVector" type="{}T_Code10" minOccurs="0"/>
 *                   &lt;element name="NotShowingFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="SaleReturnTypeCode" type="{}T_SaleReturnTypeCode" minOccurs="0"/>
 *                   &lt;element name="AmendmentTypeCode" type="{}T_AmendmentTypeCode" minOccurs="0"/>
 *                   &lt;element name="IconID" type="{}T_IconID" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Eligibility" type="{}T_Eligibility" maxOccurs="unbounded"/>
 *         &lt;element name="Rule" type="{}T_Rule"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_Condition", propOrder = {
  "info",
  "globalData",
    "eligibility",
    "rule"
})
public class TCondition {
    @XmlElement(name = "Info") protected TInfo info;
    @XmlElement(name = "GlobalData", required = true) protected TCondition.GlobalData globalData;
    @XmlElement(name = "Eligibility", required = true) protected List<TEligibility> eligibility;
    @XmlElement(name = "Rule", required = true) protected TRule rule;

    public TInfo getInfo() {
        return info;
    }

    /**
     * Gets the value of the globalData property.
     *
     * @return
     *     possible object is
     *     {@link TCondition.GlobalData }
     *
     */
    public TCondition.GlobalData getGlobalData() {
        return globalData;
    }

    /**
     * Sets the value of the globalData property.
     *
     * @param value
     *     allowed object is
     *     {@link TCondition.GlobalData }
     *
     */
    public void setGlobalData(TCondition.GlobalData value) {
        this.globalData = value;
    }

    /**
     * Gets the value of the eligibility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eligibility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEligibility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TEligibility }
     * 
     * 
     */
    public List<TEligibility> getEligibility() {
        if (eligibility == null) {
            eligibility = new ArrayList<TEligibility>();
        }
        return this.eligibility;
    }

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link TRule }
     *     
     */
    public TRule getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRule }
     *     
     */
    public void setRule(TRule value) {
        this.rule = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ID" type="{}T_ExternalID" minOccurs="0"/>
     *         &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="Resolution" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="TypeCode" type="{}T_Code1_4"/>
     *         &lt;element name="Description" type="{}T_Description" minOccurs="0"/>
     *         &lt;element name="OperatorDisplayName" type="{}T_Name" minOccurs="0"/>
     *         &lt;element name="CustomerDisplayName" type="{}T_Name" minOccurs="0"/>
     *         &lt;element name="ReceiptPrinterName" type="{}T_Name" minOccurs="0"/>
     *         &lt;element name="TimePeriod" type="{}T_TimePeriod" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ItemDiscountControlVector" type="{}T_Code10" minOccurs="0"/>
     *         &lt;element name="NotShowingFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="SaleReturnTypeCode" type="{}T_SaleReturnTypeCode" minOccurs="0"/>
     *         &lt;element name="AmendmentTypeCode" type="{}T_AmendmentTypeCode" minOccurs="0"/>
     *         &lt;element name="IconID" type="{}T_IconID" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "sequence",
        "resolution",
        "typeCode",
        "description",
        "operatorDisplayName",
        "customerDisplayName",
        "receiptPrinterName",
        "timePeriod",
        "itemDiscountControlVector",
        "notShowingFlag",
        "saleReturnTypeCode",
        "amendmentTypeCode",
        "iconID"
    })
    public static class GlobalData {

        @XmlElement(name = "ID")
        protected String id;
        @XmlElement(name = "Sequence")
        protected long sequence;
        @XmlElement(name = "Resolution")
        protected long resolution;
        @XmlElement(name = "TypeCode", required = true)
        protected String typeCode;
        @XmlElement(name = "Description")
        protected String description;
        @XmlElement(name = "OperatorDisplayName")
        protected String operatorDisplayName;
        @XmlElement(name = "CustomerDisplayName")
        protected String customerDisplayName;
        @XmlElement(name = "ReceiptPrinterName")
        protected String receiptPrinterName;
        @XmlElement(name = "TimePeriod")
        protected List<TTimePeriod> timePeriod;
        @XmlElement(name = "ItemDiscountControlVector")
        protected String itemDiscountControlVector;
        @XmlElement(name = "NotShowingFlag")
        protected Boolean notShowingFlag;
        @XmlElement(name = "SaleReturnTypeCode")
        protected String saleReturnTypeCode;
        @XmlElement(name = "AmendmentTypeCode")
        protected String amendmentTypeCode;
        @XmlElement(name = "IconID")
        protected String iconID;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the sequence property.
         * 
         */
        public long getSequence() {
            return sequence;
        }

        /**
         * Sets the value of the sequence property.
         * 
         */
        public void setSequence(long value) {
            this.sequence = value;
        }

        /**
         * Gets the value of the resolution property.
         * 
         */
        public long getResolution() {
            return resolution;
        }

        /**
         * Sets the value of the resolution property.
         * 
         */
        public void setResolution(long value) {
            this.resolution = value;
        }

        /**
         * Gets the value of the typeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeCode() {
            return typeCode;
        }

        /**
         * Sets the value of the typeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeCode(String value) {
            this.typeCode = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the operatorDisplayName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOperatorDisplayName() {
            return operatorDisplayName;
        }

        /**
         * Sets the value of the operatorDisplayName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOperatorDisplayName(String value) {
            this.operatorDisplayName = value;
        }

        /**
         * Gets the value of the customerDisplayName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerDisplayName() {
            return customerDisplayName;
        }

        /**
         * Sets the value of the customerDisplayName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerDisplayName(String value) {
            this.customerDisplayName = value;
        }

        /**
         * Gets the value of the receiptPrinterName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReceiptPrinterName() {
            return receiptPrinterName;
        }

        /**
         * Sets the value of the receiptPrinterName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReceiptPrinterName(String value) {
            this.receiptPrinterName = value;
        }

        /**
         * Gets the value of the timePeriod property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the timePeriod property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTimePeriod().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TTimePeriod }
         * 
         * 
         */
        public List<TTimePeriod> getTimePeriod() {
            if (timePeriod == null) {
                timePeriod = new ArrayList<TTimePeriod>();
            }
            return this.timePeriod;
        }

        /**
         * Gets the value of the itemDiscountControlVector property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemDiscountControlVector() {
            return itemDiscountControlVector;
        }

        /**
         * Sets the value of the itemDiscountControlVector property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemDiscountControlVector(String value) {
            this.itemDiscountControlVector = value;
        }

        /**
         * Gets the value of the notShowingFlag property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean getNotShowingFlag() {
            return notShowingFlag;
        }

        /**
         * Sets the value of the notShowingFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setNotShowingFlag(Boolean value) {
            this.notShowingFlag = value;
        }

        /**
         * Gets the value of the saleReturnTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSaleReturnTypeCode() {
            return saleReturnTypeCode;
        }

        /**
         * Sets the value of the saleReturnTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSaleReturnTypeCode(String value) {
            this.saleReturnTypeCode = value;
        }

        /**
         * Gets the value of the amendmentTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmendmentTypeCode() {
            return amendmentTypeCode;
        }

        /**
         * Sets the value of the amendmentTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmendmentTypeCode(String value) {
            this.amendmentTypeCode = value;
        }

        /**
         * Gets the value of the iconID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIconID() {
            return iconID;
        }

        /**
         * Sets the value of the iconID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIconID(String value) {
            this.iconID = value;
        }

    }

}
