//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.27 at 09:59:54 AM MSK 
//


package cpd.utils.model.v10502;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for T_Eligibility complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_Eligibility">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="EmployeeGroupID" type="{}T_InternalNumericID"/>
 *         &lt;element name="CustomerGroupID" type="{}T_InternalCharID"/>
 *         &lt;element name="CustomerID" type="{}T_InternalCharID"/>
 *         &lt;element name="Item">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="ID" type="{}T_ItemID"/>
 *                     &lt;element name="IDList" type="{}T_ItemIDList"/>
 *                   &lt;/choice>
 *                   &lt;element name="TypeCode" type="{}T_ThresholdTypeCode"/>
 *                   &lt;choice>
 *                     &lt;sequence>
 *                       &lt;element name="ThresholdQuantity" type="{}T_Quantity" minOccurs="0"/>
 *                       &lt;element name="IntervalQuantity" type="{}T_Quantity" minOccurs="0"/>
 *                       &lt;element name="LimitQuantity" type="{}T_Quantity" minOccurs="0"/>
 *                     &lt;/sequence>
 *                     &lt;sequence>
 *                       &lt;element name="ThresholdAmount" type="{}T_Money" minOccurs="0"/>
 *                       &lt;element name="IntervalAmount" type="{}T_Money" minOccurs="0"/>
 *                       &lt;element name="LimitAmount" type="{}T_Money" minOccurs="0"/>
 *                     &lt;/sequence>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MerchandiseHierarchyGroup">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="ID" type="{}T_MerchandiseHierarchyGroupID"/>
 *                     &lt;element name="IDList" type="{}T_MerchandiseHierarchyGroupIDList"/>
 *                     &lt;element name="IntersectionList">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;choice>
 *                               &lt;element name="ID" type="{}T_MerchandiseHierarchyGroupID" maxOccurs="unbounded"/>
 *                               &lt;element name="IDList" type="{}T_MerchandiseHierarchyGroupIDList" maxOccurs="unbounded"/>
 *                             &lt;/choice>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                   &lt;element name="TypeCode" type="{}T_ThresholdTypeCode"/>
 *                   &lt;choice>
 *                     &lt;sequence>
 *                       &lt;element name="ThresholdQuantity" type="{}T_Quantity" minOccurs="0"/>
 *                       &lt;element name="IntervalQuantity" type="{}T_Quantity" minOccurs="0"/>
 *                       &lt;element name="LimitQuantity" type="{}T_Quantity" minOccurs="0"/>
 *                     &lt;/sequence>
 *                     &lt;sequence>
 *                       &lt;element name="ThresholdAmount" type="{}T_Money" minOccurs="0"/>
 *                       &lt;element name="IntervalAmount" type="{}T_Money" minOccurs="0"/>
 *                       &lt;element name="LimitAmount" type="{}T_Money" minOccurs="0"/>
 *                     &lt;/sequence>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MarketBasketThresholdAmount" type="{}T_Money"/>
 *         &lt;element name="Coupon">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID" type="{}T_InternalCharID"/>
 *                   &lt;element name="ConsumptionTypeCode" type="{}T_ConsumptionTypeCode" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ManualRebateTrigger">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="ManualTrigger">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TypeCode" type="{}T_Code2"/>
 *                             &lt;element name="Value" type="{}T_ExternalID"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="AutomaticalTrigger">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Value" type="{}T_ExternalID"/>
 *                             &lt;element name="ThresholdValue" type="{}T_Money" minOccurs="0"/>
 *                             &lt;element name="IntervalValue" type="{}T_Money" minOccurs="0"/>
 *                             &lt;element name="LimitValue" type="{}T_Money" minOccurs="0"/>
 *                             &lt;element name="PrivilegeType" type="{}T_PrivilegeType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PositionType" type="{}T_PositionType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_Eligibility", propOrder = {
    "employeeGroupID",
    "customerGroupID",
    "customerID",
    "item",
    "merchandiseHierarchyGroup",
    "marketBasketThresholdAmount",
    "coupon",
    "manualRebateTrigger",
    "positionType"
})
public class TEligibility {

    @XmlElement(name = "EmployeeGroupID")
    protected Long employeeGroupID;
    @XmlElement(name = "CustomerGroupID")
    protected String customerGroupID;
    @XmlElement(name = "CustomerID")
    protected String customerID;
    @XmlElement(name = "Item")
    protected TEligibility.Item item;
    @XmlElement(name = "MerchandiseHierarchyGroup")
    protected TEligibility.MerchandiseHierarchyGroup merchandiseHierarchyGroup;
    @XmlElement(name = "MarketBasketThresholdAmount")
    protected Double marketBasketThresholdAmount;
    @XmlElement(name = "Coupon")
    protected TEligibility.Coupon coupon;
    @XmlElement(name = "ManualRebateTrigger")
    protected TEligibility.ManualRebateTrigger manualRebateTrigger;
    @XmlElement(name = "PositionType")
    protected BigInteger positionType;

    /**
     * Gets the value of the employeeGroupID property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getEmployeeGroupID() {
        return employeeGroupID;
    }

    /**
     * Sets the value of the employeeGroupID property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setEmployeeGroupID(Long value) {
        this.employeeGroupID = value;
    }

    /**
     * Gets the value of the customerGroupID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCustomerGroupID() {
        return customerGroupID;
    }

    /**
     * Sets the value of the customerGroupID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCustomerGroupID(String value) {
        this.customerGroupID = value;
    }

    /**
     * Gets the value of the customerID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the item property.
     *
     * @return
     *     possible object is
     *     {@link TEligibility.Item }
     *
     */
    public TEligibility.Item getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     *
     * @param value
     *     allowed object is
     *     {@link TEligibility.Item }
     *
     */
    public void setItem(TEligibility.Item value) {
        this.item = value;
    }

    /**
     * Gets the value of the merchandiseHierarchyGroup property.
     *
     * @return
     *     possible object is
     *     {@link TEligibility.MerchandiseHierarchyGroup }
     *
     */
    public TEligibility.MerchandiseHierarchyGroup getMerchandiseHierarchyGroup() {
        return merchandiseHierarchyGroup;
    }

    /**
     * Sets the value of the merchandiseHierarchyGroup property.
     *
     * @param value
     *     allowed object is
     *     {@link TEligibility.MerchandiseHierarchyGroup }
     *
     */
    public void setMerchandiseHierarchyGroup(TEligibility.MerchandiseHierarchyGroup value) {
        this.merchandiseHierarchyGroup = value;
    }

    /**
     * Gets the value of the marketBasketThresholdAmount property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getMarketBasketThresholdAmount() {
        return marketBasketThresholdAmount;
    }

    /**
     * Sets the value of the marketBasketThresholdAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setMarketBasketThresholdAmount(Double value) {
        this.marketBasketThresholdAmount = value;
    }

    /**
     * Gets the value of the coupon property.
     *
     * @return
     *     possible object is
     *     {@link TEligibility.Coupon }
     *
     */
    public TEligibility.Coupon getCoupon() {
        return coupon;
    }

    /**
     * Sets the value of the coupon property.
     *
     * @param value
     *     allowed object is
     *     {@link TEligibility.Coupon }
     *
     */
    public void setCoupon(TEligibility.Coupon value) {
        this.coupon = value;
    }

    /**
     * Gets the value of the manualRebateTrigger property.
     *
     * @return
     *     possible object is
     *     {@link TEligibility.ManualRebateTrigger }
     *
     */
    public TEligibility.ManualRebateTrigger getManualRebateTrigger() {
        return manualRebateTrigger;
    }

    /**
     * Sets the value of the manualRebateTrigger property.
     *
     * @param value
     *     allowed object is
     *     {@link TEligibility.ManualRebateTrigger }
     *
     */
    public void setManualRebateTrigger(TEligibility.ManualRebateTrigger value) {
        this.manualRebateTrigger = value;
    }

    /**
     * Gets the value of the positionType property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getPositionType() {
        return positionType;
    }

    /**
     * Sets the value of the positionType property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setPositionType(BigInteger value) {
        this.positionType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ID" type="{}T_InternalCharID"/>
     *         &lt;element name="ConsumptionTypeCode" type="{}T_ConsumptionTypeCode" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "consumptionTypeCode"
    })
    public static class Coupon {

        @XmlElement(name = "ID", required = true)
        protected String id;
        @XmlElement(name = "ConsumptionTypeCode")
        protected String consumptionTypeCode;

        /**
         * Gets the value of the id property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the consumptionTypeCode property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getConsumptionTypeCode() {
            return consumptionTypeCode;
        }

        /**
         * Sets the value of the consumptionTypeCode property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setConsumptionTypeCode(String value) {
            this.consumptionTypeCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="ID" type="{}T_ItemID"/>
     *           &lt;element name="IDList" type="{}T_ItemIDList"/>
     *         &lt;/choice>
     *         &lt;element name="TypeCode" type="{}T_ThresholdTypeCode"/>
     *         &lt;choice>
     *           &lt;sequence>
     *             &lt;element name="ThresholdQuantity" type="{}T_Quantity" minOccurs="0"/>
     *             &lt;element name="IntervalQuantity" type="{}T_Quantity" minOccurs="0"/>
     *             &lt;element name="LimitQuantity" type="{}T_Quantity" minOccurs="0"/>
     *           &lt;/sequence>
     *           &lt;sequence>
     *             &lt;element name="ThresholdAmount" type="{}T_Money" minOccurs="0"/>
     *             &lt;element name="IntervalAmount" type="{}T_Money" minOccurs="0"/>
     *             &lt;element name="LimitAmount" type="{}T_Money" minOccurs="0"/>
     *           &lt;/sequence>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "idList",
        "typeCode",
        "thresholdQuantity",
        "intervalQuantity",
        "limitQuantity",
        "thresholdAmount",
        "intervalAmount",
        "limitAmount"
    })
    public static class Item {

        @XmlElement(name = "ID")
        protected String id;
        @XmlElement(name = "IDList")
        protected TItemIDList idList;
        @XmlElement(name = "TypeCode", required = true)
        protected TThresholdTypeCode typeCode;
        @XmlElement(name = "ThresholdQuantity")
        protected Double thresholdQuantity;
        @XmlElement(name = "IntervalQuantity")
        protected Double intervalQuantity;
        @XmlElement(name = "LimitQuantity")
        protected Double limitQuantity;
        @XmlElement(name = "ThresholdAmount")
        protected Double thresholdAmount;
        @XmlElement(name = "IntervalAmount")
        protected Double intervalAmount;
        @XmlElement(name = "LimitAmount")
        protected Double limitAmount;

        /**
         * Gets the value of the id property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the idList property.
         *
         * @return
         *     possible object is
         *     {@link TItemIDList }
         *
         */
        public TItemIDList getIDList() {
            return idList;
        }

        /**
         * Sets the value of the idList property.
         *
         * @param value
         *     allowed object is
         *     {@link TItemIDList }
         *
         */
        public void setIDList(TItemIDList value) {
            this.idList = value;
        }

        /**
         * Gets the value of the typeCode property.
         *
         * @return
         *     possible object is
         *     {@link TThresholdTypeCode }
         *
         */
        public TThresholdTypeCode getTypeCode() {
            return typeCode;
        }

        /**
         * Sets the value of the typeCode property.
         *
         * @param value
         *     allowed object is
         *     {@link TThresholdTypeCode }
         *
         */
        public void setTypeCode(TThresholdTypeCode value) {
            this.typeCode = value;
        }

        /**
         * Gets the value of the thresholdQuantity property.
         *
         * @return
         *     possible object is
         *     {@link Double }
         *
         */
        public Double getThresholdQuantity() {
            return thresholdQuantity;
        }

        /**
         * Sets the value of the thresholdQuantity property.
         *
         * @param value
         *     allowed object is
         *     {@link Double }
         *
         */
        public void setThresholdQuantity(Double value) {
            this.thresholdQuantity = value;
        }

        /**
         * Gets the value of the intervalQuantity property.
         *
         * @return
         *     possible object is
         *     {@link Double }
         *
         */
        public Double getIntervalQuantity() {
            return intervalQuantity;
        }

        /**
         * Sets the value of the intervalQuantity property.
         *
         * @param value
         *     allowed object is
         *     {@link Double }
         *
         */
        public void setIntervalQuantity(Double value) {
            this.intervalQuantity = value;
        }

        /**
         * Gets the value of the limitQuantity property.
         *
         * @return
         *     possible object is
         *     {@link Double }
         *
         */
        public Double getLimitQuantity() {
            return limitQuantity;
        }

        /**
         * Sets the value of the limitQuantity property.
         *
         * @param value
         *     allowed object is
         *     {@link Double }
         *
         */
        public void setLimitQuantity(Double value) {
            this.limitQuantity = value;
        }

        /**
         * Gets the value of the thresholdAmount property.
         *
         * @return
         *     possible object is
         *     {@link Double }
         *
         */
        public Double getThresholdAmount() {
            return thresholdAmount;
        }

        /**
         * Sets the value of the thresholdAmount property.
         *
         * @param value
         *     allowed object is
         *     {@link Double }
         *
         */
        public void setThresholdAmount(Double value) {
            this.thresholdAmount = value;
        }

        /**
         * Gets the value of the intervalAmount property.
         *
         * @return
         *     possible object is
         *     {@link Double }
         *
         */
        public Double getIntervalAmount() {
            return intervalAmount;
        }

        /**
         * Sets the value of the intervalAmount property.
         *
         * @param value
         *     allowed object is
         *     {@link Double }
         *
         */
        public void setIntervalAmount(Double value) {
            this.intervalAmount = value;
        }

        /**
         * Gets the value of the limitAmount property.
         *
         * @return
         *     possible object is
         *     {@link Double }
         *
         */
        public Double getLimitAmount() {
            return limitAmount;
        }

        /**
         * Sets the value of the limitAmount property.
         *
         * @param value
         *     allowed object is
         *     {@link Double }
         *
         */
        public void setLimitAmount(Double value) {
            this.limitAmount = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="ManualTrigger">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TypeCode" type="{}T_Code2"/>
     *                   &lt;element name="Value" type="{}T_ExternalID"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AutomaticalTrigger">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Value" type="{}T_ExternalID"/>
     *                   &lt;element name="ThresholdValue" type="{}T_Money" minOccurs="0"/>
     *                   &lt;element name="IntervalValue" type="{}T_Money" minOccurs="0"/>
     *                   &lt;element name="LimitValue" type="{}T_Money" minOccurs="0"/>
     *                   &lt;element name="PrivilegeType" type="{}T_PrivilegeType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "manualTrigger",
        "automaticalTrigger"
    })
    public static class ManualRebateTrigger {

        @XmlElement(name = "ManualTrigger")
        protected TEligibility.ManualRebateTrigger.ManualTrigger manualTrigger;
        @XmlElement(name = "AutomaticalTrigger")
        protected TEligibility.ManualRebateTrigger.AutomaticalTrigger automaticalTrigger;

        /**
         * Gets the value of the manualTrigger property.
         *
         * @return
         *     possible object is
         *     {@link TEligibility.ManualRebateTrigger.ManualTrigger }
         *
         */
        public TEligibility.ManualRebateTrigger.ManualTrigger getManualTrigger() {
            return manualTrigger;
        }

        /**
         * Sets the value of the manualTrigger property.
         *
         * @param value
         *     allowed object is
         *     {@link TEligibility.ManualRebateTrigger.ManualTrigger }
         *
         */
        public void setManualTrigger(TEligibility.ManualRebateTrigger.ManualTrigger value) {
            this.manualTrigger = value;
        }

        /**
         * Gets the value of the automaticalTrigger property.
         *
         * @return
         *     possible object is
         *     {@link TEligibility.ManualRebateTrigger.AutomaticalTrigger }
         *
         */
        public TEligibility.ManualRebateTrigger.AutomaticalTrigger getAutomaticalTrigger() {
            return automaticalTrigger;
        }

        /**
         * Sets the value of the automaticalTrigger property.
         *
         * @param value
         *     allowed object is
         *     {@link TEligibility.ManualRebateTrigger.AutomaticalTrigger }
         *
         */
        public void setAutomaticalTrigger(TEligibility.ManualRebateTrigger.AutomaticalTrigger value) {
            this.automaticalTrigger = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Value" type="{}T_ExternalID"/>
         *         &lt;element name="ThresholdValue" type="{}T_Money" minOccurs="0"/>
         *         &lt;element name="IntervalValue" type="{}T_Money" minOccurs="0"/>
         *         &lt;element name="LimitValue" type="{}T_Money" minOccurs="0"/>
         *         &lt;element name="PrivilegeType" type="{}T_PrivilegeType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value",
            "thresholdValue",
            "intervalValue",
            "limitValue",
            "privilegeType"
        })
        public static class AutomaticalTrigger {

            @XmlElement(name = "Value", required = true)
            protected String value;
            @XmlElement(name = "ThresholdValue")
            protected Double thresholdValue;
            @XmlElement(name = "IntervalValue")
            protected Double intervalValue;
            @XmlElement(name = "LimitValue")
            protected Double limitValue;
            @XmlElement(name = "PrivilegeType")
            protected TPrivilegeType privilegeType;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the thresholdValue property.
             *
             * @return
             *     possible object is
             *     {@link Double }
             *
             */
            public Double getThresholdValue() {
                return thresholdValue;
            }

            /**
             * Sets the value of the thresholdValue property.
             *
             * @param value
             *     allowed object is
             *     {@link Double }
             *
             */
            public void setThresholdValue(Double value) {
                this.thresholdValue = value;
            }

            /**
             * Gets the value of the intervalValue property.
             *
             * @return
             *     possible object is
             *     {@link Double }
             *
             */
            public Double getIntervalValue() {
                return intervalValue;
            }

            /**
             * Sets the value of the intervalValue property.
             *
             * @param value
             *     allowed object is
             *     {@link Double }
             *
             */
            public void setIntervalValue(Double value) {
                this.intervalValue = value;
            }

            /**
             * Gets the value of the limitValue property.
             *
             * @return
             *     possible object is
             *     {@link Double }
             *
             */
            public Double getLimitValue() {
                return limitValue;
            }

            /**
             * Sets the value of the limitValue property.
             *
             * @param value
             *     allowed object is
             *     {@link Double }
             *
             */
            public void setLimitValue(Double value) {
                this.limitValue = value;
            }

            /**
             * Gets the value of the privilegeType property.
             *
             * @return
             *     possible object is
             *     {@link TPrivilegeType }
             *
             */
            public TPrivilegeType getPrivilegeType() {
                return privilegeType;
            }

            /**
             * Sets the value of the privilegeType property.
             *
             * @param value
             *     allowed object is
             *     {@link TPrivilegeType }
             *
             */
            public void setPrivilegeType(TPrivilegeType value) {
                this.privilegeType = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TypeCode" type="{}T_Code2"/>
         *         &lt;element name="Value" type="{}T_ExternalID"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "typeCode",
            "value"
        })
        public static class ManualTrigger {

            @XmlElement(name = "TypeCode", required = true)
            protected String typeCode;
            @XmlElement(name = "Value", required = true)
            protected String value;

            /**
             * Gets the value of the typeCode property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getTypeCode() {
                return typeCode;
            }

            /**
             * Sets the value of the typeCode property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setTypeCode(String value) {
                this.typeCode = value;
            }

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="ID" type="{}T_MerchandiseHierarchyGroupID"/>
     *           &lt;element name="IDList" type="{}T_MerchandiseHierarchyGroupIDList"/>
     *           &lt;element name="IntersectionList">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;choice>
     *                     &lt;element name="ID" type="{}T_MerchandiseHierarchyGroupID" maxOccurs="unbounded"/>
     *                     &lt;element name="IDList" type="{}T_MerchandiseHierarchyGroupIDList" maxOccurs="unbounded"/>
     *                   &lt;/choice>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/choice>
     *         &lt;element name="TypeCode" type="{}T_ThresholdTypeCode"/>
     *         &lt;choice>
     *           &lt;sequence>
     *             &lt;element name="ThresholdQuantity" type="{}T_Quantity" minOccurs="0"/>
     *             &lt;element name="IntervalQuantity" type="{}T_Quantity" minOccurs="0"/>
     *             &lt;element name="LimitQuantity" type="{}T_Quantity" minOccurs="0"/>
     *           &lt;/sequence>
     *           &lt;sequence>
     *             &lt;element name="ThresholdAmount" type="{}T_Money" minOccurs="0"/>
     *             &lt;element name="IntervalAmount" type="{}T_Money" minOccurs="0"/>
     *             &lt;element name="LimitAmount" type="{}T_Money" minOccurs="0"/>
     *           &lt;/sequence>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "idList",
        "intersectionList",
        "typeCode",
        "thresholdQuantity",
        "intervalQuantity",
        "limitQuantity",
        "thresholdAmount",
        "intervalAmount",
        "limitAmount"
    })
    public static class MerchandiseHierarchyGroup {

        @XmlElement(name = "ID")
        protected String id;
        @XmlElement(name = "IDList")
        protected TMerchandiseHierarchyGroupIDList idList;
        @XmlElement(name = "IntersectionList")
        protected TEligibility.MerchandiseHierarchyGroup.IntersectionList intersectionList;
        @XmlElement(name = "TypeCode", required = true)
        protected TThresholdTypeCode typeCode;
        @XmlElement(name = "ThresholdQuantity")
        protected Double thresholdQuantity;
        @XmlElement(name = "IntervalQuantity")
        protected Double intervalQuantity;
        @XmlElement(name = "LimitQuantity")
        protected Double limitQuantity;
        @XmlElement(name = "ThresholdAmount")
        protected Double thresholdAmount;
        @XmlElement(name = "IntervalAmount")
        protected Double intervalAmount;
        @XmlElement(name = "LimitAmount")
        protected Double limitAmount;

        /**
         * Gets the value of the id property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the idList property.
         *
         * @return
         *     possible object is
         *     {@link TMerchandiseHierarchyGroupIDList }
         *
         */
        public TMerchandiseHierarchyGroupIDList getIDList() {
            return idList;
        }

        /**
         * Sets the value of the idList property.
         *
         * @param value
         *     allowed object is
         *     {@link TMerchandiseHierarchyGroupIDList }
         *
         */
        public void setIDList(TMerchandiseHierarchyGroupIDList value) {
            this.idList = value;
        }

        /**
         * Gets the value of the intersectionList property.
         *
         * @return
         *     possible object is
         *     {@link TEligibility.MerchandiseHierarchyGroup.IntersectionList }
         *
         */
        public TEligibility.MerchandiseHierarchyGroup.IntersectionList getIntersectionList() {
            return intersectionList;
        }

        /**
         * Sets the value of the intersectionList property.
         *
         * @param value
         *     allowed object is
         *     {@link TEligibility.MerchandiseHierarchyGroup.IntersectionList }
         *
         */
        public void setIntersectionList(TEligibility.MerchandiseHierarchyGroup.IntersectionList value) {
            this.intersectionList = value;
        }

        /**
         * Gets the value of the typeCode property.
         * 
         * @return
         *     possible object is
         *     {@link TThresholdTypeCode }
         *     
         */
        public TThresholdTypeCode getTypeCode() {
            return typeCode;
        }

        /**
         * Sets the value of the typeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link TThresholdTypeCode }
         *     
         */
        public void setTypeCode(TThresholdTypeCode value) {
            this.typeCode = value;
        }

        /**
         * Gets the value of the thresholdQuantity property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getThresholdQuantity() {
            return thresholdQuantity;
        }

        /**
         * Sets the value of the thresholdQuantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setThresholdQuantity(Double value) {
            this.thresholdQuantity = value;
        }

        /**
         * Gets the value of the intervalQuantity property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getIntervalQuantity() {
            return intervalQuantity;
        }

        /**
         * Sets the value of the intervalQuantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setIntervalQuantity(Double value) {
            this.intervalQuantity = value;
        }

        /**
         * Gets the value of the limitQuantity property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getLimitQuantity() {
            return limitQuantity;
        }

        /**
         * Sets the value of the limitQuantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setLimitQuantity(Double value) {
            this.limitQuantity = value;
        }

        /**
         * Gets the value of the thresholdAmount property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getThresholdAmount() {
            return thresholdAmount;
        }

        /**
         * Sets the value of the thresholdAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setThresholdAmount(Double value) {
            this.thresholdAmount = value;
        }

        /**
         * Gets the value of the intervalAmount property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getIntervalAmount() {
            return intervalAmount;
        }

        /**
         * Sets the value of the intervalAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setIntervalAmount(Double value) {
            this.intervalAmount = value;
        }

        /**
         * Gets the value of the limitAmount property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getLimitAmount() {
            return limitAmount;
        }

        /**
         * Sets the value of the limitAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setLimitAmount(Double value) {
            this.limitAmount = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="ID" type="{}T_MerchandiseHierarchyGroupID" maxOccurs="unbounded"/>
         *         &lt;element name="IDList" type="{}T_MerchandiseHierarchyGroupIDList" maxOccurs="unbounded"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "idList"
        })
        public static class IntersectionList {

            @XmlElement(name = "ID")
            protected List<String> id;
            @XmlElement(name = "IDList")
            protected List<TMerchandiseHierarchyGroupIDList> idList;

            /**
             * Gets the value of the id property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the id property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getID().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getID() {
                if (id == null) {
                    id = new ArrayList<String>();
                }
                return this.id;
            }

            /**
             * Gets the value of the idList property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the idList property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getIDList().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TMerchandiseHierarchyGroupIDList }
             * 
             * 
             */
            public List<TMerchandiseHierarchyGroupIDList> getIDList() {
                if (idList == null) {
                    idList = new ArrayList<TMerchandiseHierarchyGroupIDList>();
                }
                return this.idList;
            }

        }

    }

}
