//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.27 at 09:59:54 AM MSK 
//


package cpd.utils.model.v10502;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>Java class for T_Rule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_Rule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GlobalData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Description" type="{}T_Description" minOccurs="0"/>
 *                   &lt;element name="TransactionControlCode" type="{}T_TransactionControlCode"/>
 *                   &lt;element name="RoundingMethodCode" type="{}T_RoundingMethodCode" minOccurs="0"/>
 *                   &lt;element name="DecimalPlacesCount" type="{}T_Count" minOccurs="0"/>
 *                   &lt;element name="RebateMethod" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="NormalRebate">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="RebateAsGiftCert">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="GiftCertExpiryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                                       &lt;element name="IsCharged" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="RebateAsTender">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="TenderTypeCode" type="{}T_Code1_4"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="RebateAsCoupon">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CouponPrintoutID" type="{}T_InternalCharID"/>
 *                                       &lt;element name="CouponPrintoutRule" type="{}T_CouponPrintoutRule"/>
 *                                       &lt;element name="CouponPrintoutText" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Line" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="Text" type="{}T_CouponText"/>
 *                                                           &lt;element name="Format" type="{}T_TextFormat" maxOccurs="unbounded" minOccurs="0"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CalculationBase" type="{}T_CalculationBase" minOccurs="0"/>
 *                   &lt;element name="RoundDestinationValue" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="SimpleRebate">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="ReductionMethodCode" type="{}T_ReductionMethodCode"/>
 *                     &lt;element name="Value" type="{}T_Money"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="MixAndMatch">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="LimitCount" type="{}T_Quantity" minOccurs="0"/>
 *                     &lt;element name="CombinationCode" type="{}T_CombinationCodeMixAndMatch" minOccurs="0"/>
 *                     &lt;element name="MatchingItem" maxOccurs="unbounded">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;choice>
 *                                 &lt;element name="MerchandiseHierarchyGroupID" type="{}T_MerchandiseHierarchyGroupID"/>
 *                                 &lt;element name="ItemID" type="{}T_ItemID"/>
 *                               &lt;/choice>
 *                               &lt;element name="ReductionMethodCode" type="{}T_ReductionMethodCodeMixAndMatch"/>
 *                               &lt;element name="Value" type="{}T_Money"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Set">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="SetItem" maxOccurs="unbounded">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;choice>
 *                                 &lt;element name="MerchandiseHierarchyGroupID" type="{}T_MerchandiseHierarchyGroupID"/>
 *                                 &lt;element name="ItemID" type="{}T_ItemID"/>
 *                               &lt;/choice>
 *                               &lt;element name="MarkdownAllocationPercent" type="{}T_Percent"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="NewSetPriceAmount" type="{}T_Money"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="ToBePaidQuantity" type="{}T_Quantity"/>
 *           &lt;element name="BonusPoints">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="ReductionMethodCode" type="{}T_ReductionMethodCode"/>
 *                     &lt;element name="Value" type="{}T_Money"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="ManualRebate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *           &lt;element name="NoRebate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_Rule", propOrder = {
    "globalData",
    "simpleRebate",
    "mixAndMatch",
    "set",
    "toBePaidQuantity",
    "bonusPoints",
    "manualRebate",
    "noRebate"
})
public class TRule {

    @XmlElement(name = "GlobalData", required = true)
    protected TRule.GlobalData globalData;
    @XmlElement(name = "SimpleRebate")
    protected TRule.SimpleRebate simpleRebate;
    @XmlElement(name = "MixAndMatch")
    protected TRule.MixAndMatch mixAndMatch;
    @XmlElement(name = "Set")
    protected TRule.Set set;
    @XmlElement(name = "ToBePaidQuantity")
    protected Double toBePaidQuantity;
    @XmlElement(name = "BonusPoints")
    protected TRule.BonusPoints bonusPoints;
    @XmlElement(name = "ManualRebate")
    protected Boolean manualRebate;
    @XmlElement(name = "NoRebate")
    protected Boolean noRebate;

    /**
     * Gets the value of the globalData property.
     *
     * @return
     *     possible object is
     *     {@link TRule.GlobalData }
     *
     */
    public TRule.GlobalData getGlobalData() {
        return globalData;
    }

    /**
     * Sets the value of the globalData property.
     *
     * @param value
     *     allowed object is
     *     {@link TRule.GlobalData }
     *
     */
    public void setGlobalData(TRule.GlobalData value) {
        this.globalData = value;
    }

    /**
     * Gets the value of the simpleRebate property.
     *
     * @return
     *     possible object is
     *     {@link TRule.SimpleRebate }
     *
     */
    public TRule.SimpleRebate getSimpleRebate() {
        return simpleRebate;
    }

    /**
     * Sets the value of the simpleRebate property.
     *
     * @param value
     *     allowed object is
     *     {@link TRule.SimpleRebate }
     *
     */
    public void setSimpleRebate(TRule.SimpleRebate value) {
        this.simpleRebate = value;
    }

    /**
     * Gets the value of the mixAndMatch property.
     *
     * @return
     *     possible object is
     *     {@link TRule.MixAndMatch }
     *
     */
    public TRule.MixAndMatch getMixAndMatch() {
        return mixAndMatch;
    }

    /**
     * Sets the value of the mixAndMatch property.
     *
     * @param value
     *     allowed object is
     *     {@link TRule.MixAndMatch }
     *
     */
    public void setMixAndMatch(TRule.MixAndMatch value) {
        this.mixAndMatch = value;
    }

    /**
     * Gets the value of the set property.
     *
     * @return
     *     possible object is
     *     {@link TRule.Set }
     *
     */
    public TRule.Set getSet() {
        return set;
    }

    /**
     * Sets the value of the set property.
     *
     * @param value
     *     allowed object is
     *     {@link TRule.Set }
     *
     */
    public void setSet(TRule.Set value) {
        this.set = value;
    }

    /**
     * Gets the value of the toBePaidQuantity property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getToBePaidQuantity() {
        return toBePaidQuantity;
    }

    /**
     * Sets the value of the toBePaidQuantity property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setToBePaidQuantity(Double value) {
        this.toBePaidQuantity = value;
    }

    /**
     * Gets the value of the bonusPoints property.
     *
     * @return
     *     possible object is
     *     {@link TRule.BonusPoints }
     *
     */
    public TRule.BonusPoints getBonusPoints() {
        return bonusPoints;
    }

    /**
     * Sets the value of the bonusPoints property.
     *
     * @param value
     *     allowed object is
     *     {@link TRule.BonusPoints }
     *
     */
    public void setBonusPoints(TRule.BonusPoints value) {
        this.bonusPoints = value;
    }

    /**
     * Gets the value of the manualRebate property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean getManualRebate() {
        return manualRebate;
    }

    /**
     * Sets the value of the manualRebate property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setManualRebate(Boolean value) {
        this.manualRebate = value;
    }

    /**
     * Gets the value of the noRebate property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean getNoRebate() {
        return noRebate;
    }

    /**
     * Sets the value of the noRebate property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setNoRebate(Boolean value) {
        this.noRebate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ReductionMethodCode" type="{}T_ReductionMethodCode"/>
     *         &lt;element name="Value" type="{}T_Money"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reductionMethodCode",
        "value"
    })
    public static class BonusPoints {

        @XmlElement(name = "ReductionMethodCode", required = true)
        protected TReductionMethodCode reductionMethodCode;
        @XmlElement(name = "Value")
        protected double value;

        /**
         * Gets the value of the reductionMethodCode property.
         *
         * @return
         *     possible object is
         *     {@link TReductionMethodCode }
         *
         */
        public TReductionMethodCode getReductionMethodCode() {
            return reductionMethodCode;
        }

        /**
         * Sets the value of the reductionMethodCode property.
         *
         * @param value
         *     allowed object is
         *     {@link TReductionMethodCode }
         *
         */
        public void setReductionMethodCode(TReductionMethodCode value) {
            this.reductionMethodCode = value;
        }

        /**
         * Gets the value of the value property.
         *
         */
        public double getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         */
        public void setValue(double value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Description" type="{}T_Description" minOccurs="0"/>
     *         &lt;element name="TransactionControlCode" type="{}T_TransactionControlCode"/>
     *         &lt;element name="RoundingMethodCode" type="{}T_RoundingMethodCode" minOccurs="0"/>
     *         &lt;element name="DecimalPlacesCount" type="{}T_Count" minOccurs="0"/>
     *         &lt;element name="RebateMethod" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="NormalRebate">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="RebateAsGiftCert">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="GiftCertExpiryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *                             &lt;element name="IsCharged" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="RebateAsTender">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="TenderTypeCode" type="{}T_Code1_4"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="RebateAsCoupon">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CouponPrintoutID" type="{}T_InternalCharID"/>
     *                             &lt;element name="CouponPrintoutRule" type="{}T_CouponPrintoutRule"/>
     *                             &lt;element name="CouponPrintoutText" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Line" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="Text" type="{}T_CouponText"/>
     *                                                 &lt;element name="Format" type="{}T_TextFormat" maxOccurs="unbounded" minOccurs="0"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CalculationBase" type="{}T_CalculationBase" minOccurs="0"/>
     *         &lt;element name="RoundDestinationValue" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "transactionControlCode",
        "roundingMethodCode",
        "decimalPlacesCount",
        "rebateMethod",
        "calculationBase",
        "roundDestinationValue"
    })
    public static class GlobalData {

        @XmlElement(name = "Description")
        protected String description;
        @XmlElement(name = "TransactionControlCode", required = true)
        protected TTransactionControlCode transactionControlCode;
        @XmlElement(name = "RoundingMethodCode")
        protected String roundingMethodCode;
        @XmlElement(name = "DecimalPlacesCount")
        protected BigInteger decimalPlacesCount;
        @XmlElement(name = "RebateMethod")
        protected TRule.GlobalData.RebateMethod rebateMethod;
        @XmlElement(name = "CalculationBase")
        protected String calculationBase;
        @XmlElement(name = "RoundDestinationValue")
        protected BigInteger roundDestinationValue;

        /**
         * Gets the value of the description property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the transactionControlCode property.
         *
         * @return
         *     possible object is
         *     {@link TTransactionControlCode }
         *
         */
        public TTransactionControlCode getTransactionControlCode() {
            return transactionControlCode;
        }

        /**
         * Sets the value of the transactionControlCode property.
         *
         * @param value
         *     allowed object is
         *     {@link TTransactionControlCode }
         *
         */
        public void setTransactionControlCode(TTransactionControlCode value) {
            this.transactionControlCode = value;
        }

        /**
         * Gets the value of the roundingMethodCode property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRoundingMethodCode() {
            return roundingMethodCode;
        }

        /**
         * Sets the value of the roundingMethodCode property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRoundingMethodCode(String value) {
            this.roundingMethodCode = value;
        }

        /**
         * Gets the value of the decimalPlacesCount property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getDecimalPlacesCount() {
            return decimalPlacesCount;
        }

        /**
         * Sets the value of the decimalPlacesCount property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setDecimalPlacesCount(BigInteger value) {
            this.decimalPlacesCount = value;
        }

        /**
         * Gets the value of the rebateMethod property.
         *
         * @return
         *     possible object is
         *     {@link TRule.GlobalData.RebateMethod }
         *
         */
        public TRule.GlobalData.RebateMethod getRebateMethod() {
            return rebateMethod;
        }

        /**
         * Sets the value of the rebateMethod property.
         *
         * @param value
         *     allowed object is
         *     {@link TRule.GlobalData.RebateMethod }
         *
         */
        public void setRebateMethod(TRule.GlobalData.RebateMethod value) {
            this.rebateMethod = value;
        }

        /**
         * Gets the value of the calculationBase property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCalculationBase() {
            return calculationBase;
        }

        /**
         * Sets the value of the calculationBase property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCalculationBase(String value) {
            this.calculationBase = value;
        }

        /**
         * Gets the value of the roundDestinationValue property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getRoundDestinationValue() {
            return roundDestinationValue;
        }

        /**
         * Sets the value of the roundDestinationValue property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setRoundDestinationValue(BigInteger value) {
            this.roundDestinationValue = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="NormalRebate">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="RebateAsGiftCert">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="GiftCertExpiryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
         *                   &lt;element name="IsCharged" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="RebateAsTender">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TenderTypeCode" type="{}T_Code1_4"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="RebateAsCoupon">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CouponPrintoutID" type="{}T_InternalCharID"/>
         *                   &lt;element name="CouponPrintoutRule" type="{}T_CouponPrintoutRule"/>
         *                   &lt;element name="CouponPrintoutText" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Line" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="Text" type="{}T_CouponText"/>
         *                                       &lt;element name="Format" type="{}T_TextFormat" maxOccurs="unbounded" minOccurs="0"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "normalRebate",
            "rebateAsGiftCert",
            "rebateAsTender",
            "rebateAsCoupon"
        })
        public static class RebateMethod {

            @XmlElement(name = "NormalRebate")
            protected TRule.GlobalData.RebateMethod.NormalRebate normalRebate;
            @XmlElement(name = "RebateAsGiftCert")
            protected TRule.GlobalData.RebateMethod.RebateAsGiftCert rebateAsGiftCert;
            @XmlElement(name = "RebateAsTender")
            protected TRule.GlobalData.RebateMethod.RebateAsTender rebateAsTender;
            @XmlElement(name = "RebateAsCoupon")
            protected TRule.GlobalData.RebateMethod.RebateAsCoupon rebateAsCoupon;

            /**
             * Gets the value of the normalRebate property.
             *
             * @return
             *     possible object is
             *     {@link TRule.GlobalData.RebateMethod.NormalRebate }
             *
             */
            public TRule.GlobalData.RebateMethod.NormalRebate getNormalRebate() {
                return normalRebate;
            }

            /**
             * Sets the value of the normalRebate property.
             *
             * @param value
             *     allowed object is
             *     {@link TRule.GlobalData.RebateMethod.NormalRebate }
             *
             */
            public void setNormalRebate(TRule.GlobalData.RebateMethod.NormalRebate value) {
                this.normalRebate = value;
            }

            /**
             * Gets the value of the rebateAsGiftCert property.
             *
             * @return
             *     possible object is
             *     {@link TRule.GlobalData.RebateMethod.RebateAsGiftCert }
             *
             */
            public TRule.GlobalData.RebateMethod.RebateAsGiftCert getRebateAsGiftCert() {
                return rebateAsGiftCert;
            }

            /**
             * Sets the value of the rebateAsGiftCert property.
             *
             * @param value
             *     allowed object is
             *     {@link TRule.GlobalData.RebateMethod.RebateAsGiftCert }
             *
             */
            public void setRebateAsGiftCert(TRule.GlobalData.RebateMethod.RebateAsGiftCert value) {
                this.rebateAsGiftCert = value;
            }

            /**
             * Gets the value of the rebateAsTender property.
             *
             * @return
             *     possible object is
             *     {@link TRule.GlobalData.RebateMethod.RebateAsTender }
             *
             */
            public TRule.GlobalData.RebateMethod.RebateAsTender getRebateAsTender() {
                return rebateAsTender;
            }

            /**
             * Sets the value of the rebateAsTender property.
             *
             * @param value
             *     allowed object is
             *     {@link TRule.GlobalData.RebateMethod.RebateAsTender }
             *
             */
            public void setRebateAsTender(TRule.GlobalData.RebateMethod.RebateAsTender value) {
                this.rebateAsTender = value;
            }

            /**
             * Gets the value of the rebateAsCoupon property.
             *
             * @return
             *     possible object is
             *     {@link TRule.GlobalData.RebateMethod.RebateAsCoupon }
             *
             */
            public TRule.GlobalData.RebateMethod.RebateAsCoupon getRebateAsCoupon() {
                return rebateAsCoupon;
            }

            /**
             * Sets the value of the rebateAsCoupon property.
             *
             * @param value
             *     allowed object is
             *     {@link TRule.GlobalData.RebateMethod.RebateAsCoupon }
             *
             */
            public void setRebateAsCoupon(TRule.GlobalData.RebateMethod.RebateAsCoupon value) {
                this.rebateAsCoupon = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class NormalRebate {


            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CouponPrintoutID" type="{}T_InternalCharID"/>
             *         &lt;element name="CouponPrintoutRule" type="{}T_CouponPrintoutRule"/>
             *         &lt;element name="CouponPrintoutText" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Line" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="Text" type="{}T_CouponText"/>
             *                             &lt;element name="Format" type="{}T_TextFormat" maxOccurs="unbounded" minOccurs="0"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "couponPrintoutID",
                "couponPrintoutRule",
                "couponPrintoutText"
            })
            public static class RebateAsCoupon {

                @XmlElement(name = "CouponPrintoutID", required = true)
                protected String couponPrintoutID;
                @XmlElement(name = "CouponPrintoutRule", required = true)
                protected String couponPrintoutRule;
                @XmlElement(name = "CouponPrintoutText")
                protected TRule.GlobalData.RebateMethod.RebateAsCoupon.CouponPrintoutText couponPrintoutText;

                /**
                 * Gets the value of the couponPrintoutID property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getCouponPrintoutID() {
                    return couponPrintoutID;
                }

                /**
                 * Sets the value of the couponPrintoutID property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setCouponPrintoutID(String value) {
                    this.couponPrintoutID = value;
                }

                /**
                 * Gets the value of the couponPrintoutRule property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getCouponPrintoutRule() {
                    return couponPrintoutRule;
                }

                /**
                 * Sets the value of the couponPrintoutRule property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setCouponPrintoutRule(String value) {
                    this.couponPrintoutRule = value;
                }

                /**
                 * Gets the value of the couponPrintoutText property.
                 *
                 * @return
                 *     possible object is
                 *     {@link TRule.GlobalData.RebateMethod.RebateAsCoupon.CouponPrintoutText }
                 *
                 */
                public TRule.GlobalData.RebateMethod.RebateAsCoupon.CouponPrintoutText getCouponPrintoutText() {
                    return couponPrintoutText;
                }

                /**
                 * Sets the value of the couponPrintoutText property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link TRule.GlobalData.RebateMethod.RebateAsCoupon.CouponPrintoutText }
                 *
                 */
                public void setCouponPrintoutText(TRule.GlobalData.RebateMethod.RebateAsCoupon.CouponPrintoutText value) {
                    this.couponPrintoutText = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Line" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="Text" type="{}T_CouponText"/>
                 *                   &lt;element name="Format" type="{}T_TextFormat" maxOccurs="unbounded" minOccurs="0"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "line"
                })
                public static class CouponPrintoutText {

                    @XmlElement(name = "Line", required = true)
                    protected List<Line> line;

                    /**
                     * Gets the value of the line property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the line property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getLine().add(newItem);
                     * </pre>
                     *
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link TRule.GlobalData.RebateMethod.RebateAsCoupon.CouponPrintoutText.Line }
                     *
                     *
                     */
                    public List<Line> getLine() {
                        if (line == null) {
                            line = new ArrayList<Line>();
                        }
                        return this.line;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     *
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     *
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="Text" type="{}T_CouponText"/>
                     *         &lt;element name="Format" type="{}T_TextFormat" maxOccurs="unbounded" minOccurs="0"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     *
                     *
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "text",
                        "format"
                    })
                    public static class Line {

                        @XmlElement(name = "Text", required = true)
                        protected String text;
                        @XmlElement(name = "Format")
                        protected List<TTextFormat> format;

                        /**
                         * Gets the value of the text property.
                         *
                         * @return
                         *     possible object is
                         *     {@link String }
                         *
                         */
                        public String getText() {
                            return text;
                        }

                        /**
                         * Sets the value of the text property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *
                         */
                        public void setText(String value) {
                            this.text = value;
                        }

                        /**
                         * Gets the value of the format property.
                         *
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the format property.
                         *
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getFormat().add(newItem);
                         * </pre>
                         *
                         *
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link TTextFormat }
                         *
                         *
                         */
                        public List<TTextFormat> getFormat() {
                            if (format == null) {
                                format = new ArrayList<TTextFormat>();
                            }
                            return this.format;
                        }

                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="GiftCertExpiryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
             *         &lt;element name="IsCharged" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "giftCertExpiryDate",
                "isCharged"
            })
            public static class RebateAsGiftCert {

                @XmlElement(name = "GiftCertExpiryDate")
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar giftCertExpiryDate;
                @XmlElement(name = "IsCharged")
                protected boolean isCharged;

                /**
                 * Gets the value of the giftCertExpiryDate property.
                 *
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *
                 */
                public XMLGregorianCalendar getGiftCertExpiryDate() {
                    return giftCertExpiryDate;
                }

                /**
                 * Sets the value of the giftCertExpiryDate property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *
                 */
                public void setGiftCertExpiryDate(XMLGregorianCalendar value) {
                    this.giftCertExpiryDate = value;
                }

                /**
                 * Gets the value of the isCharged property.
                 *
                 */
                public boolean isIsCharged() {
                    return isCharged;
                }

                /**
                 * Sets the value of the isCharged property.
                 *
                 */
                public void setIsCharged(boolean value) {
                    this.isCharged = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TenderTypeCode" type="{}T_Code1_4"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tenderTypeCode"
            })
            public static class RebateAsTender {

                @XmlElement(name = "TenderTypeCode", required = true)
                protected String tenderTypeCode;

                /**
                 * Gets the value of the tenderTypeCode property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getTenderTypeCode() {
                    return tenderTypeCode;
                }

                /**
                 * Sets the value of the tenderTypeCode property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setTenderTypeCode(String value) {
                    this.tenderTypeCode = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LimitCount" type="{}T_Quantity" minOccurs="0"/>
     *         &lt;element name="CombinationCode" type="{}T_CombinationCodeMixAndMatch" minOccurs="0"/>
     *         &lt;element name="MatchingItem" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice>
     *                     &lt;element name="MerchandiseHierarchyGroupID" type="{}T_MerchandiseHierarchyGroupID"/>
     *                     &lt;element name="ItemID" type="{}T_ItemID"/>
     *                   &lt;/choice>
     *                   &lt;element name="ReductionMethodCode" type="{}T_ReductionMethodCodeMixAndMatch"/>
     *                   &lt;element name="Value" type="{}T_Money"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "limitCount",
        "combinationCode",
        "matchingItem"
    })
    public static class MixAndMatch {

        @XmlElement(name = "LimitCount")
        protected Double limitCount;
        @XmlElement(name = "CombinationCode")
        protected TCombinationCodeMixAndMatch combinationCode;
        @XmlElement(name = "MatchingItem", required = true)
        protected List<MatchingItem> matchingItem;

        /**
         * Gets the value of the limitCount property.
         *
         * @return
         *     possible object is
         *     {@link Double }
         *
         */
        public Double getLimitCount() {
            return limitCount;
        }

        /**
         * Sets the value of the limitCount property.
         *
         * @param value
         *     allowed object is
         *     {@link Double }
         *
         */
        public void setLimitCount(Double value) {
            this.limitCount = value;
        }

        /**
         * Gets the value of the combinationCode property.
         *
         * @return
         *     possible object is
         *     {@link TCombinationCodeMixAndMatch }
         *
         */
        public TCombinationCodeMixAndMatch getCombinationCode() {
            return combinationCode;
        }

        /**
         * Sets the value of the combinationCode property.
         *
         * @param value
         *     allowed object is
         *     {@link TCombinationCodeMixAndMatch }
         *
         */
        public void setCombinationCode(TCombinationCodeMixAndMatch value) {
            this.combinationCode = value;
        }

        /**
         * Gets the value of the matchingItem property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the matchingItem property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMatchingItem().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TRule.MixAndMatch.MatchingItem }
         *
         *
         */
        public List<MatchingItem> getMatchingItem() {
            if (matchingItem == null) {
                matchingItem = new ArrayList<MatchingItem>();
            }
            return this.matchingItem;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element name="MerchandiseHierarchyGroupID" type="{}T_MerchandiseHierarchyGroupID"/>
         *           &lt;element name="ItemID" type="{}T_ItemID"/>
         *         &lt;/choice>
         *         &lt;element name="ReductionMethodCode" type="{}T_ReductionMethodCodeMixAndMatch"/>
         *         &lt;element name="Value" type="{}T_Money"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "merchandiseHierarchyGroupID",
            "itemID",
            "reductionMethodCode",
            "value"
        })
        public static class MatchingItem {

            @XmlElement(name = "MerchandiseHierarchyGroupID")
            protected String merchandiseHierarchyGroupID;
            @XmlElement(name = "ItemID")
            protected String itemID;
            @XmlElement(name = "ReductionMethodCode", required = true)
            protected TReductionMethodCodeMixAndMatch reductionMethodCode;
            @XmlElement(name = "Value")
            protected double value;

            /**
             * Gets the value of the merchandiseHierarchyGroupID property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getMerchandiseHierarchyGroupID() {
                return merchandiseHierarchyGroupID;
            }

            /**
             * Sets the value of the merchandiseHierarchyGroupID property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setMerchandiseHierarchyGroupID(String value) {
                this.merchandiseHierarchyGroupID = value;
            }

            /**
             * Gets the value of the itemID property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getItemID() {
                return itemID;
            }

            /**
             * Sets the value of the itemID property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setItemID(String value) {
                this.itemID = value;
            }

            /**
             * Gets the value of the reductionMethodCode property.
             *
             * @return
             *     possible object is
             *     {@link TReductionMethodCodeMixAndMatch }
             *
             */
            public TReductionMethodCodeMixAndMatch getReductionMethodCode() {
                return reductionMethodCode;
            }

            /**
             * Sets the value of the reductionMethodCode property.
             *
             * @param value
             *     allowed object is
             *     {@link TReductionMethodCodeMixAndMatch }
             *
             */
            public void setReductionMethodCode(TReductionMethodCodeMixAndMatch value) {
                this.reductionMethodCode = value;
            }

            /**
             * Gets the value of the value property.
             *
             */
            public double getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             */
            public void setValue(double value) {
                this.value = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SetItem" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice>
     *                     &lt;element name="MerchandiseHierarchyGroupID" type="{}T_MerchandiseHierarchyGroupID"/>
     *                     &lt;element name="ItemID" type="{}T_ItemID"/>
     *                   &lt;/choice>
     *                   &lt;element name="MarkdownAllocationPercent" type="{}T_Percent"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="NewSetPriceAmount" type="{}T_Money"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "setItem",
        "newSetPriceAmount"
    })
    public static class Set {

        @XmlElement(name = "SetItem", required = true)
        protected List<SetItem> setItem;
        @XmlElement(name = "NewSetPriceAmount")
        protected double newSetPriceAmount;

        /**
         * Gets the value of the setItem property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the setItem property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSetItem().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TRule.Set.SetItem }
         *
         *
         */
        public List<SetItem> getSetItem() {
            if (setItem == null) {
                setItem = new ArrayList<SetItem>();
            }
            return this.setItem;
        }

        /**
         * Gets the value of the newSetPriceAmount property.
         * 
         */
        public double getNewSetPriceAmount() {
            return newSetPriceAmount;
        }

        /**
         * Sets the value of the newSetPriceAmount property.
         * 
         */
        public void setNewSetPriceAmount(double value) {
            this.newSetPriceAmount = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element name="MerchandiseHierarchyGroupID" type="{}T_MerchandiseHierarchyGroupID"/>
         *           &lt;element name="ItemID" type="{}T_ItemID"/>
         *         &lt;/choice>
         *         &lt;element name="MarkdownAllocationPercent" type="{}T_Percent"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "merchandiseHierarchyGroupID",
            "itemID",
            "markdownAllocationPercent"
        })
        public static class SetItem {

            @XmlElement(name = "MerchandiseHierarchyGroupID")
            protected String merchandiseHierarchyGroupID;
            @XmlElement(name = "ItemID")
            protected String itemID;
            @XmlElement(name = "MarkdownAllocationPercent", defaultValue = "0")
            protected double markdownAllocationPercent = 0.0D;

            /**
             * Gets the value of the merchandiseHierarchyGroupID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMerchandiseHierarchyGroupID() {
                return merchandiseHierarchyGroupID;
            }

            /**
             * Sets the value of the merchandiseHierarchyGroupID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMerchandiseHierarchyGroupID(String value) {
                this.merchandiseHierarchyGroupID = value;
            }

            /**
             * Gets the value of the itemID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getItemID() {
                return itemID;
            }

            /**
             * Sets the value of the itemID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setItemID(String value) {
                this.itemID = value;
            }

            /**
             * Gets the value of the markdownAllocationPercent property.
             * 
             */
            public double getMarkdownAllocationPercent() {
                return markdownAllocationPercent;
            }

            /**
             * Sets the value of the markdownAllocationPercent property.
             * 
             */
            public void setMarkdownAllocationPercent(double value) {
                this.markdownAllocationPercent = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ReductionMethodCode" type="{}T_ReductionMethodCode"/>
     *         &lt;element name="Value" type="{}T_Money"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reductionMethodCode",
        "value"
    })
    public static class SimpleRebate {

        @XmlElement(name = "ReductionMethodCode", required = true)
        protected TReductionMethodCode reductionMethodCode;
        @XmlElement(name = "Value")
        protected double value;

        /**
         * Gets the value of the reductionMethodCode property.
         * 
         * @return
         *     possible object is
         *     {@link TReductionMethodCode }
         *     
         */
        public TReductionMethodCode getReductionMethodCode() {
            return reductionMethodCode;
        }

        /**
         * Sets the value of the reductionMethodCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link TReductionMethodCode }
         *     
         */
        public void setReductionMethodCode(TReductionMethodCode value) {
            this.reductionMethodCode = value;
        }

        /**
         * Gets the value of the value property.
         * 
         */
        public double getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(double value) {
            this.value = value;
        }

    }

}
